=== KarloSpa/OTVRAC/labosi/lab/2015-16/by_unknown/gramatika.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           elementFormDefault="qualified">

    <!-- definition of simple elements -->

    <xs:element name="prvenstvo" type="championship"/>

    <xs:simpleType name="broj">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="25"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="weatherstate">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Kišovito"/>
            <xs:enumeration value="Sunčano"/>
            <xs:enumeration value="Oblačno"/>
            <xs:enumeration value="Poluoblačno"/>
            <xs:enumeration value="Grmljavina"/>
            <xs:enumeration value="Vjetrovito"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="bike">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Ducati"/>
            <xs:enumeration value="Aprilia"/>
            <xs:enumeration value="Honda"/>
            <xs:enumeration value="Suzuki"/>
            <xs:enumeration value="Yamaha"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cause">
        <xs:restriction base="xs:string">
            <xs:enumeration value="kvar"/>
            <xs:enumeration value="puknuće gume"/>
            <xs:enumeration value="izlijetanje"/>
            <xs:enumeration value="sudar"/>
            <xs:enumeration value="nije startao"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="length">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="2000"/>
            <xs:maxInclusive value="7000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="curves">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="2"/>
            <xs:maxInclusive value="25"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- definition of complex elements -->
    <xs:complexType name="championship">
        <xs:sequence>
            <xs:element name="utrka" type="race" maxOccurs="22"/>
        </xs:sequence>
        <xs:attribute name="godina" type="xs:string" use="optional" default="2016"/>
    </xs:complexType>

    <xs:complexType name="race">
        <xs:sequence>
            <xs:element name="imeutrke" type="xs:string"/>
            <xs:element name="facebookid" type="xs:string" minOccurs="0"/>
            <xs:element name="staza" type="track"/>
            <xs:element name="detaljiutrke" type="racedetails" minOccurs="0"/>
            <xs:element name="datumutrke" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="idutrka" type="broj" use="required" />
    </xs:complexType>

    <xs:complexType name="track">
        <xs:sequence>
            <xs:element name="imestaze" type="xs:string"/>
            <xs:element name="grad" type="xs:string" minOccurs="0"/>
            <xs:element name="drzava" type="xs:string"/>
            <xs:element name="detaljistaze" type="details"/>
            <xs:element name="slikastaze" type="xs:anyURI"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="details">
        <xs:sequence>
            <xs:element name="duzinakruga" type="length"/>
        </xs:sequence>
        <xs:attribute name="brojzavoja" type="curves" use="required"/>
    </xs:complexType>

    <xs:complexType name="racedetails">
        <xs:sequence>
            <xs:element name="pobjednik" type="winner"/>
            <xs:element name="odustajanje" type="DNF" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="vrijeme" type="weather" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="weather">
        <xs:sequence>
            <xs:element name="naoblaka" type="weatherstate"/>
            <xs:element name="temperatura" type="xs:positiveInteger"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="winner">
        <xs:sequence>
            <xs:element name="imepobjednika" type="xs:string"/>
            <xs:element name="prezimepobjednika" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="motorpobjednika" type="bike" use="required"/>
    </xs:complexType>

    <xs:complexType name="DNF">
        <xs:sequence>
            <xs:element name="imednf" type="xs:string"/>
            <xs:element name="prezimednf" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="uzrokdnf" type="cause" use="required"/>
    </xs:complexType>

</xs:schema>

=== KarloSpa/OTVRAC/labosi/lab/2015-16/by_unknown/podaci1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="pretvorba1.xsl"?>
<prvenstvo xmlns="http://www.w3schools.com"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.w3schools.com gramatika.xsd">

    <utrka idutrka="1">
        <imeutrke>Velika Nagrada Katra</imeutrke>
        <facebookid>1054363954625795</facebookid>
        <staza>
            <imestaze>Losail International Circuit</imestaze>
            <grad>Doha</grad>
            <drzava>Katar</drzava>
            <detaljistaze brojzavoja="16">
                <duzinakruga>5380</duzinakruga>
            </detaljistaze>
            <slikastaze>./images/tracks/Losail.svg</slikastaze>
        </staza>
        <detaljiutrke>
            <pobjednik motorpobjednika="Yamaha">
                <imepobjednika>Jorge</imepobjednika>
                <prezimepobjednika>Lorenzo</prezimepobjednika>
            </pobjednik>
            <odustajanje uzrokdnf="sudar">
                <imednf>Stefan</imednf>
                <prezimednf>Bradl</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="izlijetanje">
                <imednf>Loris</imednf>
                <prezimednf>Baz</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="izlijetanje">
                <imednf>Andrea</imednf>
                <prezimednf>Iannone</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="sudar">
                <imednf>Cal</imednf>
                <prezimednf>Crutchlow</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="kvar">
                <imednf>Yonny</imednf>
                <prezimednf>Hernandez</prezimednf>
            </odustajanje>
            <vrijeme>
                <naoblaka>Sunčano</naoblaka>
                <temperatura>29</temperatura>
            </vrijeme>
            <vrijeme>
                <naoblaka>Sunčano</naoblaka>
                <temperatura>30</temperatura>
            </vrijeme>
        </detaljiutrke>
        <datumutrke>2016-03-20</datumutrke>
    </utrka>

    <utrka idutrka="2">
        <imeutrke>Velika Nagrada Argentine</imeutrke>
        <facebookid>684509671652050</facebookid>
        <staza>
            <imestaze>Autodromo de Termas de Rio Hondo</imestaze>
            <grad>Termas de Rio Hondo</grad>
            <drzava>Argentina</drzava>
            <detaljistaze brojzavoja="14">
                <duzinakruga>4805</duzinakruga>
            </detaljistaze>
            <slikastaze>./images/tracks/Termas.svg</slikastaze>
        </staza>
        <detaljiutrke>
            <pobjednik motorpobjednika="Honda">
                <imepobjednika>Marc</imepobjednika>
                <prezimepobjednika>Marquez</prezimepobjednika>
            </pobjednik>
            <odustajanje uzrokdnf="sudar">
                <imednf>Yonny</imednf>
                <prezimednf>Hernandez</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="sudar">
                <imednf>Jack</imednf>
                <prezimednf>Miller</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="izlijetanje">
                <imednf>Jorge</imednf>
                <prezimednf>Lorenzo</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="puknuće gume">
                <imednf>Loris</imednf>
                <prezimednf>Baz</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="kvar">
                <imednf>Scott</imednf>
                <prezimednf>Redding</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="sudar">
                <imednf>Maverick</imednf>
                <prezimednf>Vinales</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="sudar">
                <imednf>Cal</imednf>
                <prezimednf>Crutchlow</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="izlijetanje">
                <imednf>Andrea</imednf>
                <prezimednf>Iannone</prezimednf>
            </odustajanje>
            <vrijeme>
                <naoblaka>Kišovito</naoblaka>
                <temperatura>23</temperatura>
            </vrijeme>
            <vrijeme>
                <naoblaka>Kišovito</naoblaka>
                <temperatura>25</temperatura>
            </vrijeme>
        </detaljiutrke>
        <datumutrke>2016-04-03</datumutrke>
    </utrka>

    <utrka idutrka="3">
        <imeutrke>Velika Nagrada Amerike</imeutrke>
        <facebookid>198450570488772</facebookid>
        <staza>
            <imestaze>Circuit Of The Americas</imestaze>
            <grad>Austin</grad>
            <drzava>Sjedinjene Američke Države</drzava>
            <detaljistaze brojzavoja="20">
                <duzinakruga>5513</duzinakruga>
            </detaljistaze>
            <slikastaze>./images/tracks/Austin.svg</slikastaze>
        </staza>
        <detaljiutrke>
            <pobjednik motorpobjednika="Honda">
                <imepobjednika>Marc</imepobjednika>
                <prezimepobjednika>Marquez</prezimepobjednika>
            </pobjednik>
            <odustajanje uzrokdnf="izlijetanje">
                <imednf>Valentino</imednf>
                <prezimednf>Rossi</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="sudar">
                <imednf>Andrea</imednf>
                <prezimednf>Dovizioso</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="kvar">
                <imednf>Dani</imednf>
                <prezimednf>Pedrosa</prezimednf>
            </odustajanje>
            <vrijeme>
                <naoblaka>Oblačno</naoblaka>
                <temperatura>24</temperatura>
            </vrijeme>
            <vrijeme>
                <naoblaka>Oblačno</naoblaka>
                <temperatura>26</temperatura>
            </vrijeme>
            <vrijeme>
                <naoblaka>Sunčano</naoblaka>
                <temperatura>28</temperatura>
            </vrijeme>
        </detaljiutrke>
        <datumutrke>2016-04-10</datumutrke>
    </utrka>

    <utrka idutrka="4">
        <imeutrke>Velika Nagrada Španjolske</imeutrke>
        <facebookid>459233414266149</facebookid>
        <staza>
            <imestaze>Circuito de Jerez</imestaze>
            <grad>Jerez</grad>
            <drzava>Španjolska</drzava>
            <detaljistaze brojzavoja="13">
                <duzinakruga>4428</duzinakruga>
            </detaljistaze>
            <slikastaze>./images/tracks/Jerez.svg</slikastaze>
        </staza>
        <detaljiutrke>
            <pobjednik motorpobjednika="Yamaha">
                <imepobjednika>Valentino</imepobjednika>
                <prezimepobjednika>Rossi</prezimepobjednika>
            </pobjednik>
            <odustajanje uzrokdnf="izlijetanje">
                <imednf>Alvaro</imednf>
                <prezimednf>Bautista</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="kvar">
                <imednf>Andrea</imednf>
                <prezimednf>Dovizioso</prezimednf>
            </odustajanje>
            <vrijeme>
                <naoblaka>Sunčano</naoblaka>
                <temperatura>26</temperatura>
            </vrijeme>
            <vrijeme>
                <naoblaka>Sunčano</naoblaka>
                <temperatura>27</temperatura>
            </vrijeme>
            <vrijeme>
                <naoblaka>Sunčano</naoblaka>
                <temperatura>27</temperatura>
            </vrijeme>
            <vrijeme>
                <naoblaka>Oblačno</naoblaka>
                <temperatura>28</temperatura>
            </vrijeme>
        </detaljiutrke>
        <datumutrke>2016-04-24</datumutrke>
    </utrka>

    <utrka idutrka="5">
        <imeutrke>Velika Nagrada Francuske</imeutrke>
        <facebookid>1724820274403437</facebookid>
        <staza>
            <imestaze>Circuit Bugatti</imestaze>
            <grad>Maine</grad>
            <drzava>Francuska</drzava>
            <detaljistaze brojzavoja="11">
                <duzinakruga>4273</duzinakruga>
            </detaljistaze>
            <slikastaze>./images/tracks/Bugatti.svg</slikastaze>
        </staza>
        <detaljiutrke>
            <pobjednik motorpobjednika="Yamaha">
                <imepobjednika>Jorge</imepobjednika>
                <prezimepobjednika>Lorenzo</prezimepobjednika>
            </pobjednik>
            <odustajanje uzrokdnf="kvar">
                <imednf>Scott</imednf>
                <prezimednf>Redding</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="izlijetanje">
                <imednf>Yonny</imednf>
                <prezimednf>Hernandez</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="izlijetanje">
                <imednf>Cal</imednf>
                <prezimednf>Crutchlow</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="izlijetanje">
                <imednf>Esteve</imednf>
                <prezimednf>Rabat</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="sudar">
                <imednf>Andrea</imednf>
                <prezimednf>Iannone</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="izlijetanje">
                <imednf>Andrea</imednf>
                <prezimednf>Dovizioso</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="izlijetanje">
                <imednf>Jack</imednf>
                <prezimednf>Miller</prezimednf>
            </odustajanje>
            <odustajanje uzrokdnf="izlijetanje">
                <imednf>Bradley</imednf>
                <prezimednf>Smith</prezimednf>
            </odustajanje>
            <vrijeme>
                <naoblaka>Sunčano</naoblaka>
                <temperatura>21</temperatura>
            </vrijeme>
            <vrijeme>
                <naoblaka>Sunčano</naoblaka>
                <temperatura>22</temperatura>
