=== KarloSpa/OTVRAC/labosi/lab-5/2010-11/by_unknown/PHP/gramatika.dtd
<!ELEMENT knjiznica (knjiga*)>

<!ELEMENT knjiga (naslov, podnaslov?, autor+, izdavac, datum_izdanja, ocjena?, nacin_distribucije?, kategorija, cijena, recenzija*)>
<!ATTLIST knjiga id ID #REQUIRED>
<!ATTLIST knjiga jezik CDATA #REQUIRED>
<!ATTLIST knjiga broj_stranica CDATA #REQUIRED>
<!ATTLIST knjiga isbn CDATA #REQUIRED>
<!ATTLIST knjiga izdanje CDATA #IMPLIED>
<!ATTLIST knjiga uvez (Tvrdi|Meki) #REQUIRED>

<!ELEMENT naslov (#PCDATA)>
<!ELEMENT podnaslov (#PCDATA)>
<!ELEMENT autor (ime, prezime)>
<!ELEMENT ime (#PCDATA)>
<!ELEMENT prezime (#PCDATA)>
<!ELEMENT izdavac (naziv)>
<!ELEMENT naziv (#PCDATA)>
<!ELEMENT datum_izdanja (dan, mjesec, godina)>
<!ELEMENT dan (#PCDATA)>
<!ELEMENT mjesec (#PCDATA)>
<!ELEMENT godina (#PCDATA)>
<!ELEMENT nacin_distribucije (#PCDATA)>
<!ELEMENT kategorija (#PCDATA)>
<!ELEMENT cijena (#PCDATA)>
<!ELEMENT ocjena (#PCDATA)>
<!ELEMENT recenzija (recenzent, sadrzaj)>
<!ELEMENT recenzent (ime, prezime)>
<!ELEMENT sadrzaj (#PCDATA)>

=== KarloSpa/OTVRAC/labosi/lab-3/2010-11/by_unknown/podaci.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE knjiznica SYSTEM "gramatika.dtd">
<?xml-stylesheet type="text/xsl" href="pretvorba.xsl" ?>

<knjiznica>
  <knjiga id="bk1" jezik="Engleski" broj_stranica="505" isbn="0036441105123" izdanje="3" uvez="Tvrdi">
    <naslov>Thinking in Java</naslov>
    <podnaslov>Learning Java programming language</podnaslov>
    <autor>
      <ime>Bruce</ime>
      <prezime>Eckel</prezime>
    </autor>
    <izdavac>
      <naziv>Prentice-Hall</naziv>
    </izdavac>
    <datum_izdanja>
      <dan>12</dan>
      <mjesec>12</mjesec>
      <godina>2005</godina>
    </datum_izdanja>
    <ocjena>5</ocjena>
    <nacin_distribucije>knjiga</nacin_distribucije>
    <kategorija>Software development</kategorija>
    <cijena>179.99kn</cijena>
    <recenzija>
      <recenzent>
        <ime>Heri</ime>
        <prezime>Poter</prezime>
      </recenzent>
      <sadrzaj>Jako dosadna knjiga. Radnja je nikakva.</sadrzaj>
    </recenzija>
    <recenzija>
      <recenzent>
        <ime>Heri</ime>
        <prezime>Poter</prezime>
      </recenzent>
      <sadrzaj>Zanimljivo-dosadna knjiga. Radnja je nikakva.</sadrzaj>
    </recenzija>
  </knjiga>
  
  <knjiga id="bk2" jezik="Hrvatski Engleski" broj_stranica="773" isbn="0036441105124" izdanje="1" uvez="Tvrdi">
    <naslov>Harry Potter</naslov>
    <podnaslov>Harry Potter and the order of phoenix</podnaslov>
    <autor>
      <ime>J.K.</ime>
      <prezime>Rowling</prezime>
    </autor>
    <izdavac>
      <naziv>Prentice-Hall</naziv>
    </izdavac>
    <datum_izdanja>
      <dan>10</dan>
      <mjesec>12</mjesec>
      <godina>2003</godina>
    </datum_izdanja>
    <ocjena>5</ocjena>
    <nacin_distribucije>knjiga</nacin_distribucije>
    <kategorija>Znanstvena fantastika</kategorija>
    <cijena>159.99kn</cijena>
    <recenzija>
      <recenzent>
        <ime>Heri</ime>
        <prezime>Poter</prezime>
      </recenzent>
      <sadrzaj>Puno bolja knjiga od prethodne.</sadrzaj>
    </recenzija>
  </knjiga>
  
  <knjiga id="bk3" jezik="Engleski" broj_stranica="145" isbn="0036441105125" izdanje="1" uvez="Meki">
    <naslov>Learning XML</naslov>
    <autor>
      <ime>Erik T.</ime>
      <prezime>Ray</prezime>
    </autor>
    <izdavac>
      <naziv>Prentice-Hall</naziv>
    </izdavac>
    <datum_izdanja>
      <dan>10</dan>
      <mjesec>12</mjesec>
      <godina>2003</godina>
    </datum_izdanja>
    <ocjena>3</ocjena>
    <nacin_distribucije>elektronička knjiga</nacin_distribucije>
    <kategorija>Software development</kategorija>
    <cijena>59.99kn</cijena>
  </knjiga>
  
  <knjiga id="bk4" jezik="Engleski" broj_stranica="345" isbn="0036441105126" izdanje="1" uvez="Tvrdi">
    <naslov>Gospodar prstenova</naslov>
    <podnaslov>Gospodar prstenova: Povratak kralja</podnaslov>
    <autor>
      <ime>John Ronald Reuel</ime>
      <prezime>Tolkien</prezime>
    </autor>
    <izdavac>
      <naziv>Algoritam</naziv>
    </izdavac>
    <datum_izdanja>
      <dan>21</dan>
      <mjesec>3</mjesec>
      <godina>1995</godina>
    </datum_izdanja>
    <ocjena>4</ocjena>
    <nacin_distribucije>knjiga</nacin_distribucije>
    <kategorija>Avanturistički roman</kategorija>
    <cijena>159.99kn</cijena>
  </knjiga>
  
  <knjiga id="bk5" jezik="Engleski Hrvatski" broj_stranica="728" isbn="0036441105127" izdanje="1" uvez="Tvrdi">
    <naslov>Pjesma leda i vatre</naslov>
    <podnaslov>Pjesma leda i vatre: Igra prijestolja</podnaslov>
    <autor>
      <ime>George R.R.</ime>
      <prezime>Martin</prezime>
    </autor>
    <izdavac>
      <naziv>Algoritam</naziv>
    </izdavac>
    <datum_izdanja>
      <dan>28</dan>
      <mjesec>7</mjesec>
      <godina>2001</godina>
    </datum_izdanja>
    <ocjena>4</ocjena>
    <nacin_distribucije>knjiga</nacin_distribucije>
    <kategorija>Avanturistički roman</kategorija>
    <cijena>259.99kn</cijena>
  </knjiga>
</knjiznica>
